server:
  servlet:
    context-path: /post/api/v1
  port: 5000
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json

spring:
  application:
    name: post-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/post
    driver-class-name: org.postgresql.Driver
    username: post
    password: post
    hikari:
      minimum-idle: 10
      maximum-pool-size: 70
      idle-timeout: 600000
      connection-test-query: SELECT 1
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        event.merge.entity_copy_observer: allow
        show_sql: false
        use_sql_comments: true
        format_sql: true
        ddl-auto: none
  flyway:
    locations: classpath:db/migration
    schemas: public
  data:
    redis:
      host: localhost
      port: 6379
      password: ""


springdoc:
  model-converters:
    pageable-converter:
      enabled: true
  show-actuator: true
  swagger-ui:
    path: "/swagger-ui"
    docExpansion: none
    enabled: true

resilience4j.ratelimiter:
  instances:
    myRateLimiter:
      limitForPeriod: 2  # количество запросов
      limitRefreshPeriod: 1m  # период обновления лимита
      timeoutDuration: 500ms  # тайм-аут на запросы, которые превышают лимит
